Delete unrelated script from index, move business logic to Tcl.
Now Tcl script can handle a lot of possible errors emerging during
retrieving ip address from Artik board. Also variable model changed to
less prone-error style.
 • Reduced number of «global» variables and upvar commands. They are
   replaced by proc's parameters
 • Now lots of variable targeted to pattern matching or regexp matching
   in expect logic has `pat` or `re` prefix.
 • Variables with similar purposes now are stored as dicts
 • Tcl script returns error codes:
   - If there's no device with name pased by argument, exit code 67 is
     returned
   - If device is unavaliable for getting output (e.g. if stdout of
     `/dev/ttyUSB<N>` is read by `tail -f` command), exit code 66 is
     returned
   - If it is impossible to scratch ip address of interface with
     provided by script's argument name, exit code 65 is returned

Script `zypper-installer` now checks whether `get-artik-ip.tcl` script
exit with non-zero status or not and handles non-zero status as common
error without checking number of exit code.

Signed-off-by: Georgiy Odisharia <math.kraut.cat@gmail.com>

diff --git a/zypper-installer b/zypper-installer
--- a/zypper-installer
+++ b/zypper-installer
@@ -77,25 +77,11 @@ _print_with_indent() {
 
 ## shellcheck disable=2154
 _prepare_artik() {
-    local _if_name
     local _ip_addr
-    local _subnet
-
-    local _IP_KEY="ip"
-    local _SUBNET_KEY="mask"
-
-    declare -a _ifaces
-    local _i=0
-
-    while read -r _if_name _ip_addr _subnet; do
-        declare -A "$_if_name"
-        _ifaces[$_i]=$_if_name
-        _if_name[$_IP_KEY]=$_ip_addr
-        _if_name[$_SUBNET_KEY]=$_subnet
-        (( _i++ ))
-    done  <"$(./get-artik-ip.tcl "$1")"
-
-    sdb connect "$1"
+    if ! _ip_addr=$(./get-artik-ip.tcl "$1"); then
+        printf "Can't get Artik's IP! Exit...\n" 2>&1 && exit 1
+    fi
+    sdb connect "$_ip_addr"
     sdb root on
 }
 
